### ISSUE TITLE
tips:一些想法和使用感受

### ISSUE THREAD

**Issue by damon7609** [Qiantigers/verifyBookSource#2]
首先，非常感谢大佬做出了书源校验工具，天下苦书源校验久矣QAQ

**Comment by damon7609** [comment]
在添加待校验书源时，求增加个拖动上传的功能，windows上使用时，要自己先找到路径，复制了路径，再跟上\书源名字xxx.json，总感觉很麻烦。。。

**Comment by damon7609** [comment]
<img width="493" alt="书源检测" src="https://user-images.githubusercontent.com/34952213/200218249-ae657671-11eb-4342-8de1-64cf27c78d04.png">
检测时，设置了40线程去跑，但是看dos窗口的检验进度似乎并不快。不太了解情况。扫描时还好，风扇不响，dos窗口显示扫描结束，到网页端查看结果后，风扇响个飞起。但很快出了结果。
![image](https://user-images.githubusercontent.com/34952213/200219660-8308a896-12ca-4816-be9e-28513548970c.png)

![image](https://user-images.githubusercontent.com/34952213/200219285-dcf60ac6-4825-4204-8986-4ff502d40f7e.png)
第二次，换了100线程跑后，dos里看到的速度明显提升了，跑完到网页端查看结果时，网页端过了7、8分钟仍未显示出结果，大概10分钟左右出了。
<img width="679" alt="书源检测3" src="https://user-images.githubusercontent.com/34952213/200219835-062e47c2-bee3-425b-bf8f-ed346d174ce3.png">
可以看出来两次检测结果不大一致(问题不大，暂且不提，可能是目标网站的原因)，但是网页结果页面一段时间内，都无法选中文字了(风扇声小后，恢复正常)

**Comment by damon7609** [comment]
![image](https://user-images.githubusercontent.com/34952213/200220300-8e9f060a-f3cf-4652-ab31-a0c88d256e11.png)
检测结果，好像是直接直接做了合并导出的到指定文件夹的，但发现两次导出结果，第二次直接覆盖了第一次的。这方面，求问大佬可以做个带时间戳的吗，表示不想之前的结果被覆盖掉

**Comment by damon7609** [comment]
另外，导出书源部分，出结果后，能做到在网页端展示的同时，进行批量编辑、美化格式、或者复选框选中某些源进行编辑，最后导出指定格式，到指定文件夹保存吗？

**Comment by damon7609** [comment]
最后一点是，我会遇到本地书源文件内，可能记录了多个重复书源地址的问题，我不清楚这方面检测后，会不会做一个去重，可以的话，大佬能做一个去重的功能吗？或者在网页端出结果展示后，用复选框等方式指出来，哪些书源重复了，可以不必合并到一起，求求了，这点我觉得很实用QAQ

**Comment by damon7609** [comment]
一点期待和展望：书源检测时，可以不局限于同时只检测一个书源文件；可以选中多个书源文件(包括本地文件形式、网址形式书源)，并发检测时，可以显示个进度条，显示下预计多久结束。最后的检测结果，可以同上面提到的，复选框选择后，合并导出？

**Comment by damon7609** [comment]
大佬神功盖世，抽空看看呗QvQ

**Comment by damon7609** [comment]
忘了，还有些小问题，比如dos界面显示的时候，会出现乱码的问题，不知道是不是里面的内容含有表情符号的缘故；不知道乱码好不好解决，或者不显示，直接用上面提到的进度条代替？

**Comment by Qiantigers** [comment]
之前没抽出心思查看，最近才知道很久没更新了。

针对你说的问题，我决定将之前的代码重写，之前写的有点随意，乱糟糟的。

现在不局限于本地文件，书源直链也是可以的。

另外直接淘汰了在web页面显示，感觉没有必要，全程在控制台进行操作。另外进度条等等，以及对校验结果进行了相关统计，算是优化阅读体验。
